Update federations_l_english.yml - PROVA
Neurone/stellaris-italian-translation pull request #23
Opened 2021-02-16 11:51 UTC by Nefando

Traduzione delle prime linee. Propongo la pull request per verificare di aver seguito bene la procedura e per verificare che il file venga caricato con il BOM attivo. Fammi sapere l'esito di entrambe le cose.

2021-02-17 13:52 UTC, Neurone commented
Ciao Nefando, direi tutto perfetto viene mantenuto anche il BOM. Una volta aperta la PR ogni nuovo push viene aggiunto alla stessa PR, finché non viene effettuato il merge. Quando raggiungi un punto secondo te consistente dimmelo così procedo con l'aggiornamento e la pubblicazione della nuova release della mod.

2021-02-17 14:07 UTC, Neurone commented
Aggiungo un livello di complessità in più su git, visto che hai agevolmente raggiunto questo ;)

Le prossime modifiche prova a farle su un branch ad hoc e non sul dev, così le varie PR possono andare in parallelo senza troppi problemi. Una volta clonato il repo, puoi usare un comando tipo:
```
git checkout -b traduzione-federations
```
in questo modo viene creato un branch chiamato `traduzione-federations` e ne viene fatto direttamente il checkout, qualunque prossima modifica andrà su quel branch. Dopo varie commit e push in funzione di quello che ti serve, potrai fare la PR da github richiedendo direttamente il merge su dev.

Una volta accettata la PR, potrai anche cancellare il branch in locale.

L'ultimo livello di _git developer_ sarà allineare il tuo repo remoto con questo repo aggiornato, contenente a quel punto anche la tua modifica ;) Prova anche questo, non sono molte istruzioni da lanciare (qui un esempio concreto https://gist.github.com/CristinaSolana/1885435) ma se hai problemi fammi sapere.

2021-02-17 15:51 UTC, Nefando commented
Ottimo, questo problema del BOM almeno è risolto.

Ti confesso che uso l'app GitHub Desktop, senza linea di comando, che per adesso ha dato i risultati sperati. Provo a fare quello che mi hai scritto sull'app, sperando di poter continuare ad usarla.

Per ricapitolare, se ho capito bene:
1 - Creo un branch `traduzione-federations` sul mio repo online, che poi posso modificare in locale.
2 - Mi gestisco in autonomia i vari commit e push dal branch in locale al branch su sito.
3 - A lavoro finito faccio una PR del branch `traduzione-federations` su mio repo direttamente sul tuo branch `dev`

Mentre per la seconda procedura (di sincronizzazione), otterrei lo stesso risultato se facessi un _Compare_ del mio repo `dev` col tuo e facendo una PR sul mio repo? Ovviamente da fare dopo un aggiornamento. Come il primo commit di questa PR, che ho fatto dopo l'ultima release della mod.

In ultimo, riguardo alla possibilità di fare il merge di queste PR per così aggiornare e pubblicare la mod, la parte già tradotta copre le Origini: ho appena cominciato a tradurre la parte della Comunità Galattica (che è da sola il 70% del file, per il resto ci sono eventi e altre parti, singolarmente meno corposi). Per me potresti caricarla, così da aggiornare anche le 2 piccole correzioni fatte a _Distant stars_ e _Necroids_, in tal modo continuo in modo pulito creando il branch `traduzione-federations` come da te suggerito. Se però vuoi attendere che abbia tradotto un altro pezzo sostanzioso (una settimana come minimo ci vorrà, il tempo disponibile è quello che è) dimmi se continuo a fare commit su questa PR o se posso già attivare la procedura con branch `traduzione-federations` apposito.

Abbi pazienza per il textwall, ma prima e meglio mi indirizzi sul giusto modo di lavorarci, e migliore sarà la gestione futura :)

2021-02-22 16:49 UTC, Neurone commented
@Nefando posso procedere quindi al merge di questa PR, corretto?

2021-02-22 17:31 UTC, Nefando commented
Vai pure, così almeno apro un branch apposta per il file l_english, che ho scoperto avere molte linee non tradotte. 
Dopo che avrai fatto il merge allineo il mio repo e vediamo se tutto va a buon fine.

2021-02-22 18:37 UTC, Neurone requested changes
A parte qualche piccola correzione mi pare tutto ok.

2021-02-22 18:37 UTC, Neurone commented on src/mod/localisation/english/l_english.yml
> +In teoria possono saldare i loro debiti ed essere liberati, ma i loro contratti sono intenzionalmente strutturati in modo da rendere questo un non-problema.§!"
Mi pare ci sia un a capo di troppo. Puoi verificare?

2021-02-22 18:37 UTC, Neurone commented on src/mod/localisation/english/federations_l_english.yml
> + TOOLTIP_SETUP_ORIGIN:0 "Seleziona un Origine per il tuo Impero."
Serve aggiungere apice per un'origine.

2021-02-22 20:19 UTC, Nefando commented
Corretti gli errori segnalati.

2021-02-24 22:01 UTC, merged